package com.israelsimulator.world;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.zip.GZIPInputStream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * island_temple: striped white/blue pavilion with a stepped gold dome, generated by
 * scripts/worldgen/gen_island_temple.py. The same template is the Epstein boss arena
 * (JeffreyEpsteinEntity.spawnEpsteinIslandDome).
 */
class IslandTempleStructureTest {

    private static final Gson GSON = new Gson();
    private static final String NBT = "data/israel_simulator/structure/island_temple.nbt";
    // Mirrors JeffreyEpsteinEntity's arena constants (kept in sync by arenaFitsInsideDome).
    private static final int FOOTING = 4, SPAWN_X = 13, SPAWN_Z = 3, PLAYER_Z = 1, DOME_R = 21, DOME_H = 27;

    @Test
    @DisplayName("island_temple has no worldgen structure of its own any more: it is part of tropical_island")
    void structureJson() {
        assertNull(getClass().getClassLoader().getResource("data/israel_simulator/worldgen/structure/island_temple.json"));
        assertNull(getClass().getClassLoader().getResource("data/israel_simulator/worldgen/structure_set/island_temples.json"));
        assertNotNull(getClass().getClassLoader().getResource(NBT), "arena template must stay");
    }

    @Test
    @DisplayName("The template loads and looks like the photo: bands, pilasters, gold dome, door, plaza, palms")
    void templateLooksLikeThePavilion() throws Exception {
        Template t = Template.load(readGzip(NBT));
        Map<String, Long> count = t.blocks.stream().filter(b -> !b.name.equals("minecraft:air"))
                .collect(Collectors.groupingBy(Block::name, Collectors.counting()));
        assertTrue(count.getOrDefault("minecraft:white_concrete", 0L) >= 150, "white bands");
        assertTrue(count.getOrDefault("minecraft:blue_concrete", 0L) >= 150, "blue bands/pilasters");
        assertTrue(count.getOrDefault("minecraft:gold_block", 0L) >= 150, "stepped gold dome");
        assertTrue(count.getOrDefault("minecraft:jungle_log", 0L) >= 30, "3-4 palms");
        assertTrue(count.getOrDefault("minecraft:quartz_stairs", 0L) >= 14, "white quartz stairs");
        assertEquals(2L, count.get("minecraft:dark_oak_door"), "arched dark oak door");
        assertEquals(2L, count.get("minecraft:raw_gold_block"), "two gold statues");
        assertTrue(count.containsKey("minecraft:ladder"), "ladder on one side");
        assertTrue(count.containsKey("minecraft:short_dry_grass") || count.containsKey("minecraft:tall_dry_grass"));
        for (String terracotta : List.of("red", "white", "pink")) {
            assertTrue(count.getOrDefault("minecraft:" + terracotta + "_terracotta", 0L) >= 30, terracotta + " chevrons");
        }
        // Rows alternate white/blue on the front wall (x=8, z=11), floor y=4..13 above the footing.
        for (int y = 4; y <= 13; y++) {
            String want = (y - 4) % 2 == 0 ? "minecraft:white_concrete" : "minecraft:blue_concrete";
            assertEquals(want, t.at(8, y + FOOTING, 11), "band row " + y);
        }
        // Arena spawn spots are on the plaza: solid floor, two blocks of air above.
        for (int x : new int[] {SPAWN_X - 4, SPAWN_X - 2, SPAWN_X, SPAWN_X + 2, SPAWN_X + 4}) {
            for (int z : new int[] {SPAWN_Z, PLAYER_Z}) {
                assertTrue(t.at(x, FOOTING, z).endsWith("_terracotta"), "plaza floor at " + x + "," + z);
                assertEquals("minecraft:air", t.at(x, FOOTING + 1, z));
                assertEquals("minecraft:air", t.at(x, FOOTING + 2, z));
            }
        }
    }

    @Test
    @DisplayName("One loot chest with a modest, existing loot table")
    void lootChest() throws Exception {
        Template t = Template.load(readGzip(NBT));
        List<Block> chests = t.blocks.stream().filter(b -> b.name.equals("minecraft:chest")).toList();
        assertEquals(1, chests.size());
        assertEquals("israel_simulator:chests/island_temple", chests.get(0).nbt.get("LootTable"));
        JsonObject loot = readJson("data/israel_simulator/loot_table/chests/island_temple.json");
        String text = loot.toString();
        assertFalse(text.contains("netherite") || text.contains("diamond") || text.contains("enchanted"),
                "loot must stay modest");
    }

    @Test
    @DisplayName("Epstein's dome places this template and the whole pavilion fits inside the glass shell")
    void arenaFitsInsideDome() throws Exception {
        String src = Files.readString(Path.of("src/main/java/com/israelsimulator/entity/boss/JeffreyEpsteinEntity.java"));
        assertTrue(src.contains("\"island_temple\""), "dome code must reference the island_temple template");
        assertTrue(src.contains("getStructureManager()") && src.contains("placeInWorld("));
        for (String c : List.of("TEMPLE_FOOTING = " + FOOTING, "ARENA_SPAWN_X = " + SPAWN_X, "ARENA_SPAWN_Z = " + SPAWN_Z,
                "ARENA_PLAYER_Z = " + PLAYER_Z, "DOME_RADIUS = " + DOME_R, "DOME_HEIGHT = " + DOME_H)) {
            assertTrue(src.contains(c), "constant changed, update this test: " + c);
        }
        Template t = Template.load(readGzip(NBT));
        int cx = t.sizeX / 2, cz = t.sizeZ / 2;
        for (Block b : t.blocks) {
            if (b.name.equals("minecraft:air") || b.y < FOOTING) continue;
            double dx = b.x - cx, dz = b.z - cz, dy = b.y - FOOTING;
            double f = (dx * dx + dz * dz) / (DOME_R * DOME_R) + dy * dy / (DOME_H * DOME_H);
            assertTrue(f < 1.0, b.name + " at " + b.x + "," + b.y + "," + b.z + " pokes through the glass dome");
        }
    }

    private JsonObject readJson(String path) throws Exception {
        InputStream in = getClass().getClassLoader().getResourceAsStream(path);
        assertNotNull(in, "Missing " + path);
        return GSON.fromJson(new InputStreamReader(in, StandardCharsets.UTF_8), JsonObject.class);
    }

    private byte[] readGzip(String path) throws Exception {
        InputStream in = getClass().getClassLoader().getResourceAsStream(path);
        assertNotNull(in, "Missing NBT: " + path);
        try (GZIPInputStream gz = new GZIPInputStream(in)) {
            return gz.readAllBytes();
        }
    }

    private record Block(String name, Map<String, Object> props, int x, int y, int z, Map<String, Object> nbt) {}

    private record Template(List<Block> blocks, int sizeX, int sizeY, int sizeZ, Map<String, String> grid) {
        String at(int x, int y, int z) {
            return grid.getOrDefault(x + "," + y + "," + z, "minecraft:air");
        }

        @SuppressWarnings("unchecked")
        static Template load(byte[] raw) throws IOException {
            DataInputStream in = new DataInputStream(new ByteArrayInputStream(raw));
            assertEquals(10, in.readByte());
            readString(in);
            Map<String, Object> root = readCompound(in);
            List<Map<String, Object>> palette = (List<Map<String, Object>>) root.get("palette");
            List<Block> out = new ArrayList<>();
            for (Map<String, Object> b : (List<Map<String, Object>>) root.get("blocks")) {
                List<Integer> pos = (List<Integer>) b.get("pos");
                Map<String, Object> state = palette.get(((Number) b.get("state")).intValue());
                Map<String, Object> props = (Map<String, Object>) state.getOrDefault("Properties", Map.of());
                out.add(new Block((String) state.get("Name"), props, pos.get(0), pos.get(1), pos.get(2),
                        (Map<String, Object>) b.get("nbt")));
            }
            List<Integer> size = (List<Integer>) root.get("size");
            Map<String, String> grid = new HashMap<>();
            for (Block b : out) grid.put(b.x + "," + b.y + "," + b.z, b.name);
            return new Template(out, size.get(0), size.get(1), size.get(2), grid);
        }
    }

    private static Map<String, Object> readCompound(DataInputStream in) throws IOException {
        Map<String, Object> map = new HashMap<>();
        while (true) {
            byte type = in.readByte();
            if (type == 0) {
                return map;
            }
            String name = readString(in);
            map.put(name, readPayload(in, type));
        }
    }

    private static Object readPayload(DataInputStream in, byte type) throws IOException {
        return switch (type) {
            case 1 -> in.readByte();
            case 2 -> in.readShort();
            case 3 -> in.readInt();
            case 4 -> in.readLong();
            case 5 -> in.readFloat();
            case 6 -> in.readDouble();
            case 7 -> {
                int len = in.readInt();
                in.skipBytes(len);
                yield new byte[0];
            }
            case 8 -> readString(in);
            case 9 -> readList(in);
            case 10 -> readCompound(in);
            case 11 -> {
                int len = in.readInt();
                for (int i = 0; i < len; i++) {
                    in.readInt();
                }
                yield new int[0];
            }
            case 12 -> {
                int len = in.readInt();
                for (int i = 0; i < len; i++) {
                    in.readLong();
                }
                yield new long[0];
            }
            default -> throw new IOException("Unsupported NBT type " + type);
        };
    }

    private static Object readList(DataInputStream in) throws IOException {
        byte elemType = in.readByte();
        int len = in.readInt();
        List<Object> list = new ArrayList<>(len);
        for (int i = 0; i < len; i++) {
            list.add(readPayload(in, elemType));
        }
        if (elemType == 3) {
            List<Integer> ints = new ArrayList<>(len);
            for (Object o : list) {
                ints.add(((Number) o).intValue());
            }
            return ints;
        }
        if (elemType == 10) {
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> compounds = (List<Map<String, Object>>) (List<?>) list;
            return compounds;
        }
        return list;
    }

    private static String readString(DataInputStream in) throws IOException {
        int len = in.readUnsignedShort();
        return new String(in.readNBytes(len), StandardCharsets.UTF_8);
    }
}
