package com.israelsimulator.world;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.zip.GZIPInputStream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Jaffa port is a multi-piece jigsaw town (clock tower square, stone alleys with stairs
 * and arches, stone houses, flea market, harbour with pier, boats and lighthouse),
 * generated by scripts/worldgen/gen_jaffa_port.py.
 */
class JaffaPortStructureTest {

    private static final Gson GSON = new Gson();
    private static final String NS = "israel_simulator:";

    private static final List<String> POOLS = List.of(
            "jaffa_port", "jaffa/streets", "jaffa/terminators", "jaffa/buildings", "jaffa/landmarks");

    private static final List<String> STREETS = List.of(
            "jaffa/alley_straight", "jaffa/alley_crossroad", "jaffa/alley_corner", "jaffa/alley_t",
            "jaffa/alley_arch", "jaffa/alley_stairs");

    private static final List<String> BUILDINGS = List.of(
            "jaffa/house_a", "jaffa/house_b", "jaffa/house_c", "jaffa/gallery_house",
            "jaffa/flea_market", "jaffa/harbour");

    @Test
    @DisplayName("jaffa_port is a beard_thin jigsaw locked to mediterranean_coast, starting at the clock square")
    void structureJson() throws Exception {
        JsonObject s = readJson("data/israel_simulator/worldgen/structure/jaffa_port.json");
        assertEquals("minecraft:jigsaw", s.get("type").getAsString());
        assertEquals("beard_thin", s.get("terrain_adaptation").getAsString());
        assertTrue(s.get("size").getAsInt() >= 5, "jigsaw depth must allow a real street network");
        JsonArray biomes = s.getAsJsonArray("biomes");
        assertEquals(1, biomes.size());
        assertEquals("israel_simulator:mediterranean_coast", biomes.get(0).getAsString());
        assertEquals(NS + "jaffa/clock_square", firstLocation("jaffa_port"));
    }

    @Test
    @DisplayName("All Jaffa pools resolve to existing pieces and the expected piece set")
    void poolsResolve() throws Exception {
        Set<String> all = new LinkedHashSet<>();
        for (String pool : POOLS) {
            JsonObject p = readJson(poolPath(pool));
            String fallback = p.get("fallback").getAsString();
            assertTrue(fallback.equals("minecraft:empty") || POOLS.contains(fallback.substring(NS.length())),
                    pool + " fallback must be empty or a Jaffa pool: " + fallback);
            for (var el : p.getAsJsonArray("elements")) {
                JsonObject e = el.getAsJsonObject().getAsJsonObject("element");
                String loc = e.get("location").getAsString();
                assertTrue(loc.startsWith(NS + "jaffa/"), loc);
                String proj = e.get("projection").getAsString();
                if (loc.endsWith("alley_stairs") || loc.endsWith("alley_arch")) {
                    assertEquals("rigid", proj, loc + " stairs/arches keep their shape");
                } else if (pool.equals("jaffa/streets") || pool.equals("jaffa/terminators")) {
                    assertEquals("terrain_matching", proj, loc + " alleys must follow the terrain");
                } else {
                    assertEquals("rigid", proj, loc + " buildings must be rigid");
                }
                all.add(loc.substring(NS.length()));
                assertNotNull(Template.load(readGzip(nbtPath(loc.substring(NS.length())))));
            }
        }
        assertTrue(all.containsAll(STREETS), "missing street pieces: " + all);
        assertTrue(all.containsAll(BUILDINGS), "missing building pieces: " + all);
    }

    @Test
    @DisplayName("Jigsaws only point at Jaffa pools; every building has one north-facing entrance")
    void jigsawWiring() throws Exception {
        List<String> pieces = new ArrayList<>(STREETS);
        pieces.add("jaffa/clock_square");
        pieces.add("jaffa/terminator");
        for (String piece : pieces) {
            Template t = Template.load(readGzip(nbtPath(piece)));
            int streetLinks = 0;
            for (Block b : t.blocks) {
                if (!b.name.equals("minecraft:jigsaw")) continue;
                String pool = (String) b.nbt.get("pool");
                assertTrue(pool.equals("minecraft:empty")
                                || POOLS.contains(pool.substring(NS.length())),
                        piece + " jigsaw targets unknown pool " + pool);
                if (!piece.equals("jaffa/clock_square") && !piece.equals("jaffa/alley_stairs")
                        && !piece.equals("jaffa/alley_arch")) {
                    assertEquals(1, b.y, piece + " jigsaws sit one above the street floor");
                }
                if ("minecraft:street".equals(b.nbt.get("name"))) streetLinks++;
            }
            assertTrue(streetLinks >= 1, piece + " must link to the street network");
        }
        for (String piece : BUILDINGS) {
            Template t = Template.load(readGzip(nbtPath(piece)));
            List<Block> jigsaws = t.blocks.stream().filter(b -> b.name.equals("minecraft:jigsaw")).toList();
            assertEquals(1, jigsaws.size(), piece + " must have exactly one entrance jigsaw");
            Block j = jigsaws.get(0);
            assertEquals("minecraft:building_entrance", j.nbt.get("name"));
            assertEquals("minecraft:empty", j.nbt.get("pool"));
            assertEquals("north_up", j.props.get("orientation"));
            assertEquals(0, j.z, piece + " entrance must be on the street-facing porch row");
            // rigid pieces carry a buried footing: the porch floor is directly below the jigsaw
            // and the footing continues down to y=0, so nothing floats on slopes
            final int jx = j.x, jy = j.y;
            assertTrue(jy >= 1, piece + " entrance jigsaw must sit above the floor");
            for (int y = 0; y < jy; y++) {
                final int yy = y;
                assertTrue(t.blocks.stream().anyMatch(b -> b.x == jx && b.y == yy && b.z == 0
                                && !b.name.equals("minecraft:air")),
                        piece + " porch/footing missing under the entrance at y=" + yy);
            }
        }
    }

    @Test
    @DisplayName("Jaffa buildings are furnished and their containers carry existing loot tables")
    void furnishedWithLoot() throws Exception {
        int containers = 0;
        List<String> pieces = new ArrayList<>(BUILDINGS);
        for (String piece : pieces) {
            Template t = Template.load(readGzip(nbtPath(piece)));
            boolean seating = false;
            for (Block b : t.blocks) {
                if (b.name.endsWith("_bed") || b.name.endsWith("_stairs") || b.name.endsWith("_slab")) {
                    seating = true;
                }
                if (!b.name.equals("minecraft:chest") && !b.name.equals("minecraft:barrel")) continue;
                containers++;
                assertNotNull(b.nbt, piece + " container without block entity");
                String loot = String.valueOf(b.nbt.get("LootTable"));
                assertTrue(loot.startsWith("israel_simulator:chests/jaffa_"), piece + " loot " + loot);
                String file = "data/israel_simulator/loot_table/" + loot.substring(NS.length()) + ".json";
                assertNotNull(getClass().getClassLoader().getResource(file), "missing loot table " + file);
                assertFalse(b.nbt.containsKey("Items"), "loot must fill on open");
            }
            assertTrue(seating, piece + " needs some furniture");
        }
        assertTrue(containers >= 10, "expected loot containers across Jaffa, got " + containers);
    }

    @Test
    @DisplayName("Jaffa pieces are real buildings, not hollow boxes")
    void piecesAreDetailed() throws Exception {
        for (String piece : BUILDINGS) {
            Template t = Template.load(readGzip(nbtPath(piece)));
            Set<String> palette = new LinkedHashSet<>();
            long solid = t.blocks.stream().filter(b -> !b.name.equals("minecraft:air")).peek(b -> palette.add(b.name)).count();
            assertTrue(solid >= 300, piece + " too small: " + solid);
            assertTrue(palette.size() >= 15, piece + " palette too plain: " + palette.size());
        }
        Template square = Template.load(readGzip(nbtPath("jaffa/clock_square")));
        assertTrue(square.blocks.stream().anyMatch(b -> b.name.equals("minecraft:prismarine_bricks")),
                "clock square keeps the jaffa_port marker");
        assertTrue(square.blocks.stream().anyMatch(b -> b.name.equals("minecraft:bell")), "clock tower belfry");
        assertTrue(square.blocks.stream().filter(b -> b.y > 15).count() > 10, "the clock tower must be tall");
        Template harbour = Template.load(readGzip(nbtPath("jaffa/harbour")));
        assertTrue(harbour.blocks.stream().filter(b -> b.name.equals("minecraft:water")).count() > 500,
                "harbour basin must hold water");
        assertTrue(harbour.blocks.stream().anyMatch(b -> b.name.equals("minecraft:sea_lantern")), "lighthouse lamp");
        assertTrue(harbour.blocks.stream().filter(b -> b.name.equals("minecraft:spruce_planks")).count() > 40,
                "wooden pier and boat hulls");
        Template stairs = Template.load(readGzip(nbtPath("jaffa/alley_stairs")));
        assertTrue(stairs.blocks.stream().filter(b -> b.name.equals("minecraft:stone_brick_stairs")).count() >= 12,
                "stair lane");
    }

    private String firstLocation(String pool) throws Exception {
        return readJson(poolPath(pool)).getAsJsonArray("elements").get(0).getAsJsonObject()
                .getAsJsonObject("element").get("location").getAsString();
    }

    private static String poolPath(String pool) {
        return "data/israel_simulator/worldgen/template_pool/" + pool + ".json";
    }

    private static String nbtPath(String piece) {
        return "data/israel_simulator/structure/" + piece + ".nbt";
    }

    private JsonObject readJson(String path) throws Exception {
        InputStream in = getClass().getClassLoader().getResourceAsStream(path);
        assertNotNull(in, "Missing " + path);
        return GSON.fromJson(new InputStreamReader(in, StandardCharsets.UTF_8), JsonObject.class);
    }

    private byte[] readGzip(String path) throws Exception {
        InputStream in = getClass().getClassLoader().getResourceAsStream(path);
        assertNotNull(in, "Missing NBT: " + path);
        try (GZIPInputStream gz = new GZIPInputStream(in)) {
            return gz.readAllBytes();
        }
    }

    private record Block(String name, Map<String, Object> props, int x, int y, int z, Map<String, Object> nbt) {}

    private record Template(List<Block> blocks) {
        @SuppressWarnings("unchecked")
        static Template load(byte[] raw) throws IOException {
            DataInputStream in = new DataInputStream(new ByteArrayInputStream(raw));
            assertEquals(10, in.readByte());
            readString(in);
            Map<String, Object> root = readCompound(in);
            List<Map<String, Object>> palette = (List<Map<String, Object>>) root.get("palette");
            List<Block> out = new ArrayList<>();
            for (Map<String, Object> b : (List<Map<String, Object>>) root.get("blocks")) {
                List<Integer> pos = (List<Integer>) b.get("pos");
                Map<String, Object> state = palette.get(((Number) b.get("state")).intValue());
                Map<String, Object> props = (Map<String, Object>) state.getOrDefault("Properties", Map.of());
                out.add(new Block((String) state.get("Name"), props, pos.get(0), pos.get(1), pos.get(2),
                        (Map<String, Object>) b.get("nbt")));
            }
            return new Template(out);
        }
    }

    private static Map<String, Object> readCompound(DataInputStream in) throws IOException {
        Map<String, Object> map = new HashMap<>();
        while (true) {
            byte type = in.readByte();
            if (type == 0) {
                return map;
            }
            String name = readString(in);
            map.put(name, readPayload(in, type));
        }
    }

    private static Object readPayload(DataInputStream in, byte type) throws IOException {
        return switch (type) {
            case 1 -> in.readByte();
            case 2 -> in.readShort();
            case 3 -> in.readInt();
            case 4 -> in.readLong();
            case 5 -> in.readFloat();
            case 6 -> in.readDouble();
            case 7 -> {
                int len = in.readInt();
                in.skipBytes(len);
                yield new byte[0];
            }
            case 8 -> readString(in);
            case 9 -> readList(in);
            case 10 -> readCompound(in);
            case 11 -> {
                int len = in.readInt();
                for (int i = 0; i < len; i++) {
                    in.readInt();
                }
                yield new int[0];
            }
            case 12 -> {
                int len = in.readInt();
                for (int i = 0; i < len; i++) {
                    in.readLong();
                }
                yield new long[0];
            }
            default -> throw new IOException("Unsupported NBT type " + type);
        };
    }

    private static Object readList(DataInputStream in) throws IOException {
        byte elemType = in.readByte();
        int len = in.readInt();
        List<Object> list = new ArrayList<>(len);
        for (int i = 0; i < len; i++) {
            list.add(readPayload(in, elemType));
        }
        if (elemType == 3) {
            List<Integer> ints = new ArrayList<>(len);
            for (Object o : list) {
                ints.add(((Number) o).intValue());
            }
            return ints;
        }
        if (elemType == 10) {
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> compounds = (List<Map<String, Object>>) (List<?>) list;
            return compounds;
        }
        return list;
    }

    private static String readString(DataInputStream in) throws IOException {
        int len = in.readUnsignedShort();
        return new String(in.readNBytes(len), StandardCharsets.UTF_8);
    }
}
